// constants.ts
import { Artifact } from './types';

export const GEMINI_MODEL_FLASH = 'gemini-2.5-flash';
export const GEMINI_MODEL_PRO = 'gemini-2.5-pro';
export const GEMINI_MODEL_IMAGE = 'gemini-2.5-flash-image';

// Initial ARTIFACTS data. This will be used as a fallback if no data is found in localStorage.
export const INITIAL_ARTIFACTS: Artifact[] = [
  {
    id: 'mona-lisa',
    name: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: '1503-1519',
    initialDescription: 'A half-length portrait painting by Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world".',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg',
    location: { lat: 48.8606, lng: 2.3376, city: 'Paris', country: 'France' },
    videoUrl: 'https://www.youtube.com/embed/Iurx3314n1w', // Example YouTube embed
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Mona_Lisa_Audio.ogg', // Example audio file
    category: 'Painting',
    materials: ['Oil on poplar panel'],
    dimensions: '77 cm × 53 cm',
    museum: 'Louvre Museum',
  },
  {
    id: 'starry-night',
    name: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: '1889',
    initialDescription: 'An oil-on-canvas painting by the Dutch Post-Impressionist painter Vincent van Gogh. Painted during his stay at the asylum of Saint-Paul-de-Mausole near Saint-Rémy-de-Provence, France, it depicts the view from the east-facing window of his asylum room at night, though it was painted from memory during the day.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/800px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    location: { lat: 40.7614, lng: -73.9776, city: 'New York', country: 'USA' },
    videoUrl: 'https://www.youtube.com/embed/fD-Uq4C_3J0',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Mona_Lisa_Audio.ogg',
    category: 'Painting',
    materials: ['Oil on canvas'],
    dimensions: '73.7 cm × 92.1 cm',
    museum: 'Museum of Modern Art (MoMA)',
  },
  {
    id: 'girl-with-pearl-earring',
    name: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: 'c. 1665',
    initialDescription: 'An oil painting by Dutch Golden Age painter Johannes Vermeer. It is a tronie (Dutch for "face", a 17th-century Dutch type of painting of a head or face not intended as a portrait) of a young woman wearing a headscarf and a pearl earring.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg',
    location: { lat: 52.0799, lng: 4.3142, city: 'The Hague', country: 'Netherlands' },
    videoUrl: 'https://www.youtube.com/embed/EP-J-1m9B6Q',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Mona_Lisa_Audio.ogg',
    category: 'Painting',
    materials: ['Oil on canvas'],
    dimensions: '44.5 cm × 39 cm',
    museum: 'Mauritshuis',
  },
  {
    id: 'bust-of-nefertiti',
    name: 'Bust of Nefertiti',
    artist: 'Thutmose',
    year: 'c. 1345 BC',
    initialDescription: 'A painted stucco-coated limestone bust of Nefertiti, the Great Royal Wife of Egyptian Pharaoh Akhenaten. It is one of the most copied works of ancient Egypt.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Nofretete_Neues_Museum.jpg/800px-Nofretete_Neues_Museum.jpg',
    location: { lat: 52.5170, lng: 13.3900, city: 'Berlin', country: 'Germany' },
    category: 'Sculpture',
    materials: ['Painted stucco-coated limestone'],
    dimensions: '48 cm (19 in) high',
    museum: 'Neues Museum',
  },
  {
    id: 'terracotta-army',
    name: 'Terracotta Army',
    artist: 'Unknown',
    year: 'c. 210 BC',
    initialDescription: 'A collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first Emperor of China. It is a form of funerary art buried with the emperor in 210–209 BCE with the purpose of protecting the emperor in his afterlife.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Terracotta_Army_-_Xi%27an.jpg/800px-Terracotta_Army_-_Xi%27an.jpg',
    location: { lat: 34.3853, lng: 109.2743, city: 'Xi\'an', country: 'China' },
    category: 'Sculpture',
    materials: ['Terracotta'],
    dimensions: 'Life-size figures (1.75 - 1.95m tall)',
    museum: 'Museum of Qin Terracotta Warriors and Horses',
  },
  {
    id: 'venus-de-milo',
    name: 'Venus de Milo',
    artist: 'Alexandros of Antioch',
    year: 'c. 130-100 BC',
    initialDescription: 'An ancient Greek statue from the Hellenistic period, depicting Aphrodite, the Greek goddess of love (known in Roman mythology as Venus). It is one of the most famous works of ancient Greek sculpture.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Venus_de_Milo_Louvre_MR325.jpg/800px-Venus_de_Milo_Louvre_MR325.jpg',
    location: { lat: 48.8606, lng: 2.3376, city: 'Paris', country: 'France' },
    category: 'Sculpture',
    materials: ['Parian marble'],
    dimensions: '203 cm (6 ft 8 in) tall',
    museum: 'Louvre Museum',
  },
  {
    id: 'rosetta-stone',
    name: 'Rosetta Stone',
    artist: 'Unknown',
    year: '196 BC',
    initialDescription: 'A stele composed of granodiorite inscribed with a decree issued at Memphis, Egypt, in 196 BC on behalf of King Ptolemy V Epiphanes. The decree appears in three scripts: ancient Egyptian hieroglyphs, Demotic script, and ancient Greek.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Rosetta_Stone_BW.jpg/800px-Rosetta_Stone_BW.jpg',
    location: { lat: 51.5195, lng: -0.1269, city: 'London', country: 'UK' },
    category: 'Artifact',
    materials: ['Granodiorite'],
    dimensions: '112 cm × 75.7 cm × 28.4 cm',
    museum: 'British Museum',
  },
  {
    id: 'sistine-chapel-ceiling',
    name: 'Sistine Chapel Ceiling',
    artist: 'Michelangelo',
    year: '1508-1512',
    initialDescription: 'A masterpiece by Michelangelo, comprising fresco paintings that form the ceiling of the Sistine Chapel in the Vatican City. It depicts nine scenes from the Book of Genesis, including the famous Creation of Adam.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Sistine_chapel_ceiling_-_frescoes_by_Michelangelo_Buonarroti.jpg/800px-Sistine_chapel_ceiling_-_frescoes_by_Michelangelo_Buonarroti.jpg',
    location: { lat: 41.9029, lng: 12.4534, city: 'Vatican City', country: 'Vatican City' },
    category: 'Fresco',
    materials: ['Fresco'],
    dimensions: '40 m × 13 m (ceiling area)',
    museum: 'Vatican Museums',
  },
  {
    id: 'david-statue',
    name: 'David (Michelangelo)',
    artist: 'Michelangelo',
    year: '1501-1504',
    initialDescription: 'A masterpiece of Renaissance sculpture created in marble by Italian artist Michelangelo. The 5.17-meter (17.0 ft) marble statue portrays the Biblical hero David, a favored subject in the art of Florence.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/David_von_Michelangelo.jpg/800px-David_von_Michelangelo.jpg',
    location: { lat: 43.7766, lng: 11.2520, city: 'Florence', country: 'Italy' },
    category: 'Sculpture',
    materials: ['Carrara marble'],
    dimensions: '5.17 m (17.0 ft) tall',
    museum: 'Galleria dell\'Accademia',
  },
  {
    id: 'the-scream',
    name: 'The Scream',
    artist: 'Edvard Munch',
    year: '1893',
    initialDescription: 'The popular name given to a composition created by Norwegian Expressionist artist Edvard Munch. The agonized face in the painting has become one of the most iconic images of art, seen as symbolizing the anxiety of the modern human condition.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_The_Scream%2C_1893%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_The_Scream%2C_1893%2C_National_Gallery_of_Norway.jpg',
    location: { lat: 59.9139, lng: 10.7522, city: 'Oslo', country: 'Norway' },
    category: 'Painting',
    materials: ['Oil, tempera, pastel on cardboard'],
    dimensions: '91 cm × 73.5 cm',
    museum: 'National Museum / Munch Museum',
  },
];